[phases.install]
cmds = [
  "npm install --include=dev --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run build --prefix server"
]

[start]
cmd = "server/node_modules/.bin/tsx server/index.ts"
